id: A9949739B
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
pechas:
- ICE4EE12C
- IED41FAD5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:01:23.977350
  last_modified_at: 2023-01-04 13:01:23.977372
  collections:
  - Marpa Lotsāwa Series
  - Works of Tibetan Masters
alignment_to_base:
  ICE4EE12C/419A: 4A4C
  IED41FAD5/A05C: 4A4C
